import type { Metadata } from "next";
import { Reddit_Sans, Space_Grotesk } from "next/font/google";
import "../styles/globals.css";
import Image from "next/image";

const redditSans = Reddit_Sans({
    variable: "--font-reddit-sans",
    subsets: ["latin"],
})

const groteske = Space_Grotesk({
    variable: "--font-groteske",
    subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${redditSans.variable} ${groteske.variable} antialiased`}
      >
      <div className="absolute top-0 left-0 w-full">
          <Image
              src="/bg_img.png"
              alt="Background"
              width={1920}
              height={400}
              className="w-full h-auto object-cover"
              priority
          />
      </div>
        {children}
      </body>
    </html>
  );
}
