import type { Metadata } from "next";
import { Reddit_Sans, Space_Grotesk } from "next/font/google";
import "../styles/globals.css";

const redditSans = Reddit_Sans({
    variable: "--font-reddit-sans",
    subsets: ["latin"],
})

const groteske = Space_Grotesk({
    variable: "--font-groteske",
    subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${redditSans.variable} ${groteske.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
